export type SurahStatus = 'not_started' | 'in_progress' | 'memorized' | 'needs_revision';

export interface Surah {
  n: number;
  ar: string;
  fr: string;
  juz: number;
  ayahs: number;
}

export const SURAHS: Surah[] = [
  { n: 1,   ar: "الفاتحة",    fr: "Al-Fatiha",      juz: 1,  ayahs: 7   },
  { n: 2,   ar: "البقرة",     fr: "Al-Baqara",      juz: 1,  ayahs: 286 },
  { n: 3,   ar: "آل عمران",   fr: "Ali Imran",       juz: 3,  ayahs: 200 },
  { n: 4,   ar: "النساء",     fr: "An-Nisa",        juz: 4,  ayahs: 176 },
  { n: 5,   ar: "المائدة",    fr: "Al-Ma'ida",      juz: 6,  ayahs: 120 },
  { n: 6,   ar: "الأنعام",    fr: "Al-An'am",       juz: 7,  ayahs: 165 },
  { n: 7,   ar: "الأعراف",    fr: "Al-A'raf",       juz: 8,  ayahs: 206 },
  { n: 8,   ar: "الأنفال",    fr: "Al-Anfal",       juz: 9,  ayahs: 75  },
  { n: 9,   ar: "التوبة",     fr: "At-Tawba",       juz: 10, ayahs: 129 },
  { n: 10,  ar: "يونس",       fr: "Yunus",          juz: 11, ayahs: 109 },
  { n: 11,  ar: "هود",        fr: "Hud",            juz: 11, ayahs: 123 },
  { n: 12,  ar: "يوسف",       fr: "Yusuf",          juz: 12, ayahs: 111 },
  { n: 13,  ar: "الرعد",      fr: "Ar-Ra'd",        juz: 13, ayahs: 43  },
  { n: 14,  ar: "إبراهيم",    fr: "Ibrahim",        juz: 13, ayahs: 52  },
  { n: 15,  ar: "الحجر",      fr: "Al-Hijr",        juz: 13, ayahs: 99  },
  { n: 16,  ar: "النحل",      fr: "An-Nahl",        juz: 14, ayahs: 128 },
  { n: 17,  ar: "الإسراء",    fr: "Al-Isra",        juz: 15, ayahs: 111 },
  { n: 18,  ar: "الكهف",      fr: "Al-Kahf",        juz: 15, ayahs: 110 },
  { n: 19,  ar: "مريم",       fr: "Maryam",         juz: 16, ayahs: 98  },
  { n: 20,  ar: "طه",         fr: "Ta-Ha",          juz: 16, ayahs: 135 },
  { n: 21,  ar: "الأنبياء",   fr: "Al-Anbiya",      juz: 17, ayahs: 112 },
  { n: 22,  ar: "الحج",       fr: "Al-Hajj",        juz: 17, ayahs: 78  },
  { n: 23,  ar: "المؤمنون",   fr: "Al-Mu'minun",    juz: 18, ayahs: 118 },
  { n: 24,  ar: "النور",      fr: "An-Nur",         juz: 18, ayahs: 64  },
  { n: 25,  ar: "الفرقان",    fr: "Al-Furqan",      juz: 18, ayahs: 77  },
  { n: 26,  ar: "الشعراء",    fr: "Ash-Shu'ara",    juz: 19, ayahs: 227 },
  { n: 27,  ar: "النمل",      fr: "An-Naml",        juz: 19, ayahs: 93  },
  { n: 28,  ar: "القصص",      fr: "Al-Qasas",       juz: 20, ayahs: 88  },
  { n: 29,  ar: "العنكبوت",   fr: "Al-Ankabut",     juz: 20, ayahs: 69  },
  { n: 30,  ar: "الروم",      fr: "Ar-Rum",         juz: 21, ayahs: 60  },
  { n: 31,  ar: "لقمان",      fr: "Luqman",         juz: 21, ayahs: 34  },
  { n: 32,  ar: "السجدة",     fr: "As-Sajda",       juz: 21, ayahs: 30  },
  { n: 33,  ar: "الأحزاب",    fr: "Al-Ahzab",       juz: 21, ayahs: 73  },
  { n: 34,  ar: "سبأ",        fr: "Saba",           juz: 22, ayahs: 54  },
  { n: 35,  ar: "فاطر",       fr: "Fatir",          juz: 22, ayahs: 45  },
  { n: 36,  ar: "يس",         fr: "Ya-Sin",         juz: 22, ayahs: 83  },
  { n: 37,  ar: "الصافات",    fr: "As-Saffat",      juz: 23, ayahs: 182 },
  { n: 38,  ar: "ص",          fr: "Sad",            juz: 23, ayahs: 88  },
  { n: 39,  ar: "الزمر",      fr: "Az-Zumar",       juz: 23, ayahs: 75  },
  { n: 40,  ar: "غافر",       fr: "Ghafir",         juz: 24, ayahs: 85  },
  { n: 41,  ar: "فصلت",       fr: "Fussilat",       juz: 24, ayahs: 54  },
  { n: 42,  ar: "الشورى",     fr: "Ash-Shura",      juz: 25, ayahs: 53  },
  { n: 43,  ar: "الزخرف",     fr: "Az-Zukhruf",     juz: 25, ayahs: 89  },
  { n: 44,  ar: "الدخان",     fr: "Ad-Dukhan",      juz: 25, ayahs: 59  },
  { n: 45,  ar: "الجاثية",    fr: "Al-Jathiya",     juz: 25, ayahs: 37  },
  { n: 46,  ar: "الأحقاف",    fr: "Al-Ahqaf",       juz: 26, ayahs: 35  },
  { n: 47,  ar: "محمد",       fr: "Muhammad",       juz: 26, ayahs: 38  },
  { n: 48,  ar: "الفتح",      fr: "Al-Fath",        juz: 26, ayahs: 29  },
  { n: 49,  ar: "الحجرات",    fr: "Al-Hujurat",     juz: 26, ayahs: 18  },
  { n: 50,  ar: "ق",          fr: "Qaf",            juz: 26, ayahs: 45  },
  { n: 51,  ar: "الذاريات",   fr: "Adh-Dhariyat",   juz: 26, ayahs: 60  },
  { n: 52,  ar: "الطور",      fr: "At-Tur",         juz: 27, ayahs: 49  },
  { n: 53,  ar: "النجم",      fr: "An-Najm",        juz: 27, ayahs: 62  },
  { n: 54,  ar: "القمر",      fr: "Al-Qamar",       juz: 27, ayahs: 55  },
  { n: 55,  ar: "الرحمن",     fr: "Ar-Rahman",      juz: 27, ayahs: 78  },
  { n: 56,  ar: "الواقعة",    fr: "Al-Waqi'a",      juz: 27, ayahs: 96  },
  { n: 57,  ar: "الحديد",     fr: "Al-Hadid",       juz: 27, ayahs: 29  },
  { n: 58,  ar: "المجادلة",   fr: "Al-Mujadila",    juz: 28, ayahs: 22  },
  { n: 59,  ar: "الحشر",      fr: "Al-Hashr",       juz: 28, ayahs: 24  },
  { n: 60,  ar: "الممتحنة",   fr: "Al-Mumtahina",   juz: 28, ayahs: 13  },
  { n: 61,  ar: "الصف",       fr: "As-Saf",         juz: 28, ayahs: 14  },
  { n: 62,  ar: "الجمعة",     fr: "Al-Jumu'a",      juz: 28, ayahs: 11  },
  { n: 63,  ar: "المنافقون",  fr: "Al-Munafiqun",   juz: 28, ayahs: 11  },
  { n: 64,  ar: "التغابن",    fr: "At-Taghabun",    juz: 28, ayahs: 18  },
  { n: 65,  ar: "الطلاق",     fr: "At-Talaq",       juz: 28, ayahs: 12  },
  { n: 66,  ar: "التحريم",    fr: "At-Tahrim",      juz: 28, ayahs: 12  },
  { n: 67,  ar: "الملك",      fr: "Al-Mulk",        juz: 29, ayahs: 30  },
  { n: 68,  ar: "القلم",      fr: "Al-Qalam",       juz: 29, ayahs: 52  },
  { n: 69,  ar: "الحاقة",     fr: "Al-Haqqah",      juz: 29, ayahs: 52  },
  { n: 70,  ar: "المعارج",    fr: "Al-Ma'arij",     juz: 29, ayahs: 44  },
  { n: 71,  ar: "نوح",        fr: "Nuh",            juz: 29, ayahs: 28  },
  { n: 72,  ar: "الجن",       fr: "Al-Jinn",        juz: 29, ayahs: 28  },
  { n: 73,  ar: "المزمل",     fr: "Al-Muzzammil",   juz: 29, ayahs: 20  },
  { n: 74,  ar: "المدثر",     fr: "Al-Muddathir",   juz: 29, ayahs: 56  },
  { n: 75,  ar: "القيامة",    fr: "Al-Qiyama",      juz: 29, ayahs: 40  },
  { n: 76,  ar: "الإنسان",    fr: "Al-Insan",       juz: 29, ayahs: 31  },
  { n: 77,  ar: "المرسلات",   fr: "Al-Mursalat",    juz: 29, ayahs: 50  },
  { n: 78,  ar: "النبأ",      fr: "An-Naba",        juz: 30, ayahs: 40  },
  { n: 79,  ar: "النازعات",   fr: "An-Nazi'at",     juz: 30, ayahs: 46  },
  { n: 80,  ar: "عبس",        fr: "Abasa",          juz: 30, ayahs: 42  },
  { n: 81,  ar: "التكوير",    fr: "At-Takwir",      juz: 30, ayahs: 29  },
  { n: 82,  ar: "الانفطار",   fr: "Al-Infitar",     juz: 30, ayahs: 19  },
  { n: 83,  ar: "المطففين",   fr: "Al-Mutaffifin",  juz: 30, ayahs: 36  },
  { n: 84,  ar: "الانشقاق",   fr: "Al-Inshiqaq",    juz: 30, ayahs: 25  },
  { n: 85,  ar: "البروج",     fr: "Al-Buruj",       juz: 30, ayahs: 22  },
  { n: 86,  ar: "الطارق",     fr: "At-Tariq",       juz: 30, ayahs: 17  },
  { n: 87,  ar: "الأعلى",     fr: "Al-Ala",         juz: 30, ayahs: 19  },
  { n: 88,  ar: "الغاشية",    fr: "Al-Ghashiya",    juz: 30, ayahs: 26  },
  { n: 89,  ar: "الفجر",      fr: "Al-Fajr",        juz: 30, ayahs: 30  },
  { n: 90,  ar: "البلد",      fr: "Al-Balad",       juz: 30, ayahs: 20  },
  { n: 91,  ar: "الشمس",      fr: "Ash-Shams",      juz: 30, ayahs: 15  },
  { n: 92,  ar: "الليل",      fr: "Al-Layl",        juz: 30, ayahs: 21  },
  { n: 93,  ar: "الضحى",      fr: "Ad-Duha",        juz: 30, ayahs: 11  },
  { n: 94,  ar: "الشرح",      fr: "Ash-Sharh",      juz: 30, ayahs: 8   },
  { n: 95,  ar: "التين",      fr: "At-Tin",         juz: 30, ayahs: 8   },
  { n: 96,  ar: "العلق",      fr: "Al-Alaq",        juz: 30, ayahs: 19  },
  { n: 97,  ar: "القدر",      fr: "Al-Qadr",        juz: 30, ayahs: 5   },
  { n: 98,  ar: "البينة",     fr: "Al-Bayyina",     juz: 30, ayahs: 8   },
  { n: 99,  ar: "الزلزلة",    fr: "Az-Zalzala",     juz: 30, ayahs: 8   },
  { n: 100, ar: "العاديات",   fr: "Al-Adiyat",      juz: 30, ayahs: 11  },
  { n: 101, ar: "القارعة",    fr: "Al-Qari'a",      juz: 30, ayahs: 11  },
  { n: 102, ar: "التكاثر",    fr: "At-Takathur",    juz: 30, ayahs: 8   },
  { n: 103, ar: "العصر",      fr: "Al-Asr",         juz: 30, ayahs: 3   },
  { n: 104, ar: "الهمزة",     fr: "Al-Humaza",      juz: 30, ayahs: 9   },
  { n: 105, ar: "الفيل",      fr: "Al-Fil",         juz: 30, ayahs: 5   },
  { n: 106, ar: "قريش",       fr: "Quraysh",        juz: 30, ayahs: 4   },
  { n: 107, ar: "الماعون",    fr: "Al-Ma'un",       juz: 30, ayahs: 7   },
  { n: 108, ar: "الكوثر",     fr: "Al-Kawthar",     juz: 30, ayahs: 3   },
  { n: 109, ar: "الكافرون",   fr: "Al-Kafirun",     juz: 30, ayahs: 6   },
  { n: 110, ar: "النصر",      fr: "An-Nasr",        juz: 30, ayahs: 3   },
  { n: 111, ar: "المسد",      fr: "Al-Masad",       juz: 30, ayahs: 5   },
  { n: 112, ar: "الإخلاص",    fr: "Al-Ikhlas",      juz: 30, ayahs: 4   },
  { n: 113, ar: "الفلق",      fr: "Al-Falaq",       juz: 30, ayahs: 5   },
  { n: 114, ar: "الناس",      fr: "An-Nas",         juz: 30, ayahs: 6   },
];

export const JUZ_SURAHS: Surah[][] = Array.from({ length: 30 }, (_, i) =>
  SURAHS.filter((s) => s.juz === i + 1)
);

export function countMemorized(memo: Record<number, SurahStatus>): number {
  return Object.values(memo).filter((s) => s === "memorized").length;
}
